starting multiply, got the logic down

diff --git a/program1/matrix b/program1/matrix
--- a/program1/matrix
+++ b/program1/matrix
@@ -125,6 +125,7 @@ add() {
 		echo "error, file unreadable" 1>&2
 		return 1
 
+	#if columns and rows of both matrices are not the same send error
 	elif [ $cols1 != $cols2 ] || [ $rows1 != $rows2 ]
 	then 
 		echo "error, dimensions are not the same" 1>&2
@@ -161,7 +162,45 @@ add() {
 }
 
 multiply() {
-	echo multiply
+	if [ $# -gt 2 ];
+	then
+		echo "error, too many arguments" 1>&2
+		return 1
+
+	elif  { [ ! -r $1 ] || [ ! -r $2 ]; } && [ $# -eq 2 ]
+	then
+		echo "error, file unreadable" 1>&2
+		return 1
+
+	else
+		transpose $2 > "right_trans_temp$$"
+		
+		# i=1 #incrementors
+		# j=1
+		sum=0
+
+		while read -u 3 left_matrix
+		do
+			row1_element=$(cut -f $i <<< "$left_matrix")
+			echo $row1_element
+
+			#echo $left_matrix
+			while read -u 4 right_matrix
+			do
+
+				#for loop to iterate through rows at the same time
+				#put into sum
+
+			done 4<"right_trans_temp$$"
+
+		done 3<"$1"
+
+		return 0
+	fi
+}
+
+trap() {
+	echo "use this function to remove temp files"
 }
 
 #main
